### ISSUE TITLE
```bomber``` should fail gracefully with a readable error message if an SBOM cannot be marshalled

### ISSUE THREAD

**Issue by jnylund** [devops-kung-fu/bomber#160] opened 2023-04-17 17:22 UTC
Hi,
when I try to run with: bomber scan bom.xml --debug

I get:
Version: 0.4.4
2023/04/17 13:19:28 Reading: bom.xml
2023/04/17 13:19:28 WARNING: bom.xml isn't a valid SBOM

It ran on my first bom.xml, but when I updated my code to current and regenerated my bom.xml, this version it doesn't seem to be able to parse.

I don't want to post the full bom.xml for security reasons on here, but here is the first part...

```
<?xml version="1.0" encoding="UTF-8"?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.1" version="1" serialNumber="urn:uuid:27998121-26de-4542-a627-ddfc5cddda90">
  <components>
    <component type="library">
      <name>Ascii85</name>
      <version>1.0.2</version>
      <description>Ascii85 encoder/decoder</description>
      <hashes>
        <hash alg="SHA-256">f854f2ebb0bd13f80ee9018a904357175337cfe0816ecb60466ca2d0fad22549</hash>
      </hashes>
      <purl>pkg:gem/Ascii85@1.0.2</purl>
    </component>
    <component type="library">
      <name>actioncable</name>
      <version>5.2.5</version>
      <description>WebSocket framework for Rails.</description>
      <hashes>
        <hash alg="SHA-256">3771ca29ee67914eda1b5de3d66a0c4bb0250bb244d76e8690dc5af2ff10e699</hash>
      </hashes>
      <licenses>
        <license>
          <id>MIT</id>
        </license>
      </licenses>
      <purl>pkg:gem/actioncable@5.2.5</purl>
    </component>
```
Any suggestions?

**Comment by djschleen** [comment] 2023-04-25 04:29
@jnylund  I'll take a look at this - also make sure I have some automated testing in place to ensure XML format is working. We mostly use JSON in our tests. Can you try converting the file to JSON and re-running the bomber? What app was used to generate the XML?

**Comment by djschleen** [comment] 2023-05-15 21:00
Going to rename this issue. We'll add better messaging for errors around converting XML or JSON format to the CycloneDX structs. Bomber uses the latest CycloneDX spec version and updates with every commit to a newer version if available.

**Comment by djschleen** [comment] 2023-11-21 21:37
I can't reproduce this one after the new refactoring and error handling. Closing, but feel free to reopen if you are still seeing this.

**Closed by djschleen** 2023-11-21 21:37 UTC
